# Catppuccin Mocha Palette
# Blue: #89b4fa
# Surface0: #313244
# Base: #1e1e2e
# Mantle: #181825
# Text: #cdd6f4
# Mauve: #cba6f7

format = "[](#89b4fa)[  ](bg:#89b4fa fg:#1e1e2e)[](bg:#313244 fg:#89b4fa)$directory[](fg:#313244 bg:#1e1e2e)$git_branch$git_status[](fg:#1e1e2e bg:#181825)$nodejs$rust$golang$php[](fg:#181825)\n$character"

[directory]
style = "fg:#cdd6f4 bg:#313244"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#1e1e2e"
format = '[[ $symbol $branch ](fg:#cba6f7 bg:#1e1e2e)]($style)'

[git_status]
style = "bg:#1e1e2e"
format = '[[($all_status$ahead_behind )](fg:#cba6f7 bg:#1e1e2e)]($style)'

[nodejs]
symbol = ""
style = "bg:#181825"
format = '[[ $symbol ($version) ](fg:#a6e3a1 bg:#181825)]($style)'

[rust]
symbol = ""
style = "bg:#181825"
format = '[[ $symbol ($version) ](fg:#fab387 bg:#181825)]($style)'

[golang]
symbol = "ﳑ"
style = "bg:#181825"
format = '[[ $symbol ($version) ](fg:#89dceb bg:#181825)]($style)'

[php]
symbol = ""
style = "bg:#181825"
format = '[[ $symbol ($version) ](fg:#89b4fa bg:#181825)]($style)'

[time]
disabled = true
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#a0a9cb bg:#1d2230)]($style)'

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"